version: "3.0"

services:
    wg-easy:
        environment:
            - WG_HOST=${EXTERNAL_IP}
            - PASSWORD=${WG_UI_PASSWORD}
            - WG_DEFAULT_DNS=10.8.1.3
            - WG_DEFAULT_ADDRESS=10.8.0.x
            - CORS_LIST=${WG_CORS_LIST}
        image: wg-easy
        #image: weejewel/wg-easy
        container_name: wg-easy
        volumes:
            - ~/.wg-easy:/etc/wireguard
        ports:
            - "51820:51820/udp"
            - "51821:51821/tcp"
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            wg-easy:
                ipv4_address: 10.8.1.2

    pihole:
        container_name: pihole
        image: cbcrowe/pihole-unbound:latest
        restart: unless-stopped
        networks:
            wg-easy:
                ipv4_address: 10.8.1.3
        ports:
            - 127.0.0.1:53:53/tcp
            - 127.0.0.1:53:53/udp
            - 127.0.0.1:67:67/udp
            - 3141:80/tcp
        environment:
            ServerIP: 10.8.1.3
            TZ: Europe/London
            WEBPASSWORD: ${PH_UI_PASSWORD}
            REV_SERVER: "false"
            DNS1: 127.0.0.1#5335
            DNS2: 127.0.0.1#5335
            DNSSEC: "true"
            QUERY_LOGGING: "false"
            WEBUIBOXEDLAYOUT: "traditional"
            FTLCONF_PRIVACYLEVEL: 3
            FTLCONF_MAXDBDAYS: 0
        volumes:
            - /home/server/data/pihole/etc-pihole/:/etc/pihole:rw
            - /home/server/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d:rw
        labels:
            com.centurylinklabs.watchtower.enable: "true"

networks:
    wg-easy:
        ipam:
            config:
                - subnet: 10.8.1.0/24
